# Pacman configuration file
# Change values here to tune the game.

# UI params
tile_size = 16
ui_height = 80

# Game logic
starting_lives = 3
starting_timer_ms = 200000
power_up_score = 5

# Game tick delay
game_tick_delay_ms = 300

# Entities positions
pacman_start_x = 13
pacman_start_y = 9
ghost1_start_x = 15
ghost1_start_y = 1
ghost2_start_x = 15
ghost2_start_y = 18
ghost3_start_x = 1
ghost3_start_y = 1
ghost4_start_x = 1
ghost4_start_y = 18
