#include "ghost.h"
#include <iostream>
#include <cstdlib>
#include <ctime>

using namespace std;

void init_ghost(SGhost &ghost, int x, int y)
{
    ghost.last_move='L';
    ghost.ifcookie=1;
    ghost.if_boost=0;
    ghost.xg=x;
    ghost.yg=y;
    ghost.lp=1;
}

void ghost_move(SGhost &ghost, SMap &map){

    //tutaj tworze ruchy ducha

    int x=ghost.xg, y=ghost.yg;

    int possible=0;                                 //zmienna na możliwości ruchu ducha
    int up=0, down=0, left=0, right=0;

    if(map.map[x-1][y]!='x'&&map.map[x-1][y]!='A'){        //jeśli na górze nie ma 'x' i 'A'
        possible++;
        up=1;
    }
    if(map.map[x+1][y]!='x'&&map.map[x+1][y]!='A'){        //jeśli na dole nie ma 'x' i 'A'
        possible++;
        down=1;
    }
    if(map.map[x][y-1]!='x'&&map.map[x][y-1]!='A'){        //jeśli z prawej nie ma 'x' i 'A'
        possible++;
        left=1;
    }
    if(map.map[x][y+1]!='x'&&map.map[x][y+1]!='A'){        //jeśli z lewej nie ma 'x' i 'A'
        possible++;
        right=1;
    }

    if(possible==1||possible==2)
    {
        if(ghost.last_move=='L')
        {
            if(left)
            {
                if(ghost.ifcookie!=0)
                {
                    map.map[x][y]='.';
                    y--;
                }
                if(ghost.if_boost!=0)
                {
                    map.map[x][y]='e';
                    y--;
                }
                if(ghost.ifcookie==0&&ghost.if_boost==0)
                {
                    map.map[x][y]=' ';
                    y--;
                }
                if(map.map[x][y]=='.')
                    ghost.ifcookie=1;
                else
                    ghost.ifcookie=0;
                if(map.map[x][y]=='e')
                    ghost.if_boost=1;
                else
                    ghost.if_boost=0;
            }
            else
                if(down)
                {
                    if(ghost.ifcookie!=0)
                    {
                        map.map[x][y]='.';
                        x++;
                        ghost.last_move='R';
                    }
                    if(ghost.if_boost!=0)
                    {
                        map.map[x][y]='e';
                        x++;
                        ghost.last_move='R';
                    }
                    if(ghost.ifcookie==0&&ghost.if_boost==0)
                    {
                        map.map[x][y]=' ';
                        x++;
                        ghost.last_move='R';
                    }
                    if(map.map[x][y]=='.')
                        ghost.ifcookie=1;
                    else
                        ghost.ifcookie=0;
                    if(map.map[x][y]=='e')
                        ghost.if_boost=1;
                    else
                        ghost.if_boost=0;
                }
            else
                    if(up)
                    {
                        if(ghost.ifcookie!=0)
                        {
                            map.map[x][y]='.';
                            x--;
                            ghost.last_move='U';
                        }
                        if(ghost.if_boost!=0)
                        {
                            map.map[x][y]='e';
                            x--;
                            ghost.last_move='U';
                        }
                        if(ghost.ifcookie==0&&ghost.if_boost==0)
                        {
                            map.map[x][y]=' ';
                            x--;
                            ghost.last_move='U';
                        }
                        if(map.map[x][y]=='.')
                            ghost.ifcookie=1;
                        else
                            ghost.ifcookie=0;
                        if(map.map[x][y]=='e')
                            ghost.if_boost=1;
                        else
                            ghost.if_boost=0;
                    }
            else
                        if(right)
                        {
                            if(ghost.ifcookie!=0)
                            {
                                map.map[x][y]='.';
                                y++;
                                ghost.last_move='D';
                            }
                            if(ghost.if_boost!=0)
                            {
                                map.map[x][y]='e';
                                y++;
                                ghost.last_move='D';
                            }
                            if(ghost.ifcookie==0&&ghost.if_boost==0)
                            {
                                map.map[x][y]=' ';
                                y++;
                                ghost.last_move='D';
                            }
                            if(map.map[x][y]=='.')
                                ghost.ifcookie=1;
                            else
                                ghost.ifcookie=0;
                            if(map.map[x][y]=='e')
                                ghost.if_boost=1;
                            else
                                ghost.if_boost=0;
                        }
        }
        else
            if(ghost.last_move=='R')
            {
              if(right)
                {
                    if(ghost.ifcookie!=0)
                    {
                     map.map[x][y]='.';
                        y++;
                    }
                    if(ghost.if_boost!=0)
                    {
                        map.map[x][y]='e';
                        y++;
                    }
                    if(ghost.ifcookie==0&&ghost.if_boost==0)
                    {
                        map.map[x][y]=' ';
                        y++;
                 }
                 if(map.map[x][y]=='.')
                        ghost.ifcookie=1;
                 else
                     ghost.ifcookie=0;
                    if(map.map[x][y]=='e')
                     ghost.if_boost=1;
                    else
                        ghost.if_boost=0;
               }
              else
                  if(down)
                  {
                     if(ghost.ifcookie!=0)
                     {
                        map.map[x][y]='.';
                        x++;
                        ghost.last_move='R';
                    }
                    if(ghost.if_boost!=0)
                    {
                        map.map[x][y]='e';
                        x++;
                        ghost.last_move='R';
                    }
                    if(ghost.ifcookie==0&&ghost.if_boost==0)
                    {
                        map.map[x][y]=' ';
                        x++;
                        ghost.last_move='R';
                    }
                    if(map.map[x][y]=='.')
                        ghost.ifcookie=1;
                    else
                        ghost.ifcookie=0;
                    if(map.map[x][y]=='e')
                        ghost.if_boost=1;
                    else
                        ghost.if_boost=0;
                }
            else
                    if(up)
                    {
                        if(ghost.ifcookie!=0)
                        {
                            map.map[x][y]='.';
                            x--;
                            ghost.last_move='U';
                        }
                        if(ghost.if_boost!=0)
                        {
                            map.map[x][y]='e';
                            x--;
                            ghost.last_move='U';
                        }
                        if(ghost.ifcookie==0&&ghost.if_boost==0)
                        {
                            map.map[x][y]=' ';
                            x--;
                            ghost.last_move='U';
                        }
                        if(map.map[x][y]=='.')
                            ghost.ifcookie=1;
                        else
                            ghost.ifcookie=0;
                        if(map.map[x][y]=='e')
                            ghost.if_boost=1;
                        else
                            ghost.if_boost=0;
                    }
            else
                        if(left)
                        {
                            if(ghost.ifcookie!=0)
                            {
                                map.map[x][y]='.';
                                y--;
                                ghost.last_move='D';
                            }
                            if(ghost.if_boost!=0)
                            {
                                map.map[x][y]='e';
                                y--;
                                ghost.last_move='D';
                            }
                            if(ghost.ifcookie==0&&ghost.if_boost==0)
                            {
                                map.map[x][y]=' ';
                                y--;
                                ghost.last_move='D';
                            }
                            if(map.map[x][y]=='.')
                                ghost.ifcookie=1;
                            else
                                ghost.ifcookie=0;
                            if(map.map[x][y]=='e')
                                ghost.if_boost=1;
                            else
                                ghost.if_boost=0;
                        }
        }
        else
                if(ghost.last_move=='U')
                {
                    if(up)
                    {
                        if(ghost.ifcookie!=0)
                        {
                            map.map[x][y]='.';
                            x--;
                        }
                        if(ghost.if_boost!=0)
                        {
                            map.map[x][y]='e';
                            x--;
                        }
                        if(ghost.ifcookie==0&&ghost.if_boost==0)
                        {
                            map.map[x][y]=' ';
                            x--;
                        }
                        if(map.map[x][y]=='.')
                            ghost.ifcookie=1;
                        else
                            ghost.ifcookie=0;
                        if(map.map[x][y]=='e')
                            ghost.if_boost=1;
                        else
                            ghost.if_boost=0;
                    }
                    else
                        if(right)
                        {
                            if(ghost.ifcookie!=0)
                            {
                                map.map[x][y]='.';
                                y++;
                                ghost.last_move='R';
                            }
                            if(ghost.if_boost!=0)
                            {
                                map.map[x][y]='e';
                                y++;
                                ghost.last_move='R';
                            }
                            if(ghost.ifcookie==0&&ghost.if_boost==0)
                            {
                                map.map[x][y]=' ';
                                y++;
                                ghost.last_move='R';
                            }
                            if(map.map[x][y]=='.')
                                ghost.ifcookie=1;
                            else
                                ghost.ifcookie=0;
                            if(map.map[x][y]=='e')
                                ghost.if_boost=1;
                            else
                                ghost.if_boost=0;
                        }
                    else
                            if(left)
                            {
                                if(ghost.ifcookie!=0)
                                {
                                    map.map[x][y]='.';
                                    y--;
                                    ghost.last_move='L';
                                }
                                if(ghost.if_boost!=0)
                                {
                                    map.map[x][y]='e';
                                    y--;
                                    ghost.last_move='L';
                                }
                                if(ghost.ifcookie==0&&ghost.if_boost==0)
                                {
                                    map.map[x][y]=' ';
                                    y--;
                                    ghost.last_move='L';
                                }
                                if(map.map[x][y]=='.')
                                    ghost.ifcookie=1;
                                else
                                    ghost.ifcookie=0;
                                if(map.map[x][y]=='e')
                                    ghost.if_boost=1;
                                else
                                    ghost.if_boost=0;
                            }
                    else
                                if(down)
                                {
                                    if(ghost.ifcookie!=0)
                                    {
                                        map.map[x][y]='.';
                                        x++;
                                        ghost.last_move='D';
                                    }
                                    if(ghost.if_boost!=0)
                                    {
                                        map.map[x][y]='e';
                                        x++;
                                        ghost.last_move='D';
                                    }
                                    if(ghost.ifcookie==0&&ghost.if_boost==0)
                                    {
                                        map.map[x][y]=' ';
                                        x++;
                                        ghost.last_move='D';
                                    }
                                    if(map.map[x][y]=='.')
                                        ghost.ifcookie=1;
                                    else
                                        ghost.ifcookie=0;
                                    if(map.map[x][y]=='e')
                                        ghost.if_boost=1;
                                    else
                                        ghost.if_boost=0;
                                }
                }
        else
                    if(ghost.last_move=='D')
                    {
                        if(down)
                        {
                            if(ghost.ifcookie!=0)
                            {
                                map.map[x][y]='.';
                                x++;
                            }
                            if(ghost.if_boost!=0)
                            {
                                map.map[x][y]='e';
                                x++;
                            }
                            if(ghost.ifcookie==0&&ghost.if_boost==0)
                            {
                                map.map[x][y]=' ';
                                x++;
                            }
                            if(map.map[x][y]=='.')
                                ghost.ifcookie=1;
                            else
                                ghost.ifcookie=0;
                            if(map.map[x][y]=='e')
                                ghost.if_boost=1;
                            else
                                ghost.if_boost=0;
                        }
                        else
                            if(right)
                            {
                                if(ghost.ifcookie!=0)
                                {
                                    map.map[x][y]='.';
                                    y++;
                                    ghost.last_move='R';
                                }
                                if(ghost.if_boost!=0)
                                {
                                    map.map[x][y]='e';
                                    y++;
                                    ghost.last_move='R';
                                }
                                if(ghost.ifcookie==0&&ghost.if_boost==0)
                                {
                                    map.map[x][y]=' ';
                                    y++;
                                    ghost.last_move='R';
                                }
                                if(map.map[x][y]=='.')
                                    ghost.ifcookie=1;
                                else
                                    ghost.ifcookie=0;
                                if(map.map[x][y]=='e')
                                    ghost.if_boost=1;
                                else
                                    ghost.if_boost=0;
                            }
                        else
                                if(up)
                                {
                                    if(ghost.ifcookie!=0)
                                    {
                                        map.map[x][y]='.';
                                        x--;
                                        ghost.last_move='U';
                                    }
                                    if(ghost.if_boost!=0)
                                    {
                                        map.map[x][y]='e';
                                        x--;
                                        ghost.last_move='U';
                                    }
                                    if(ghost.ifcookie==0&&ghost.if_boost==0)
                                    {
                                        map.map[x][y]=' ';
                                        x--;
                                        ghost.last_move='U';
                                    }
                                    if(map.map[x][y]=='.')
                                        ghost.ifcookie=1;
                                    else
                                        ghost.ifcookie=0;
                                    if(map.map[x][y]=='e')
                                        ghost.if_boost=1;
                                    else
                                        ghost.if_boost=0;
                                }
                        else
                                    if(left)
                                    {
                                        if(ghost.ifcookie!=0)
                                        {
                                            map.map[x][y]='.';
                                            y--;
                                            ghost.last_move='L';
                                        }
                                        if(ghost.if_boost!=0)
                                        {
                                            map.map[x][y]='e';
                                            y--;
                                            ghost.last_move='L';
                                        }
                                        if(ghost.ifcookie==0&&ghost.if_boost==0)
                                        {
                                            map.map[x][y]=' ';
                                            y--;
                                            ghost.last_move='L';
                                        }
                                        if(map.map[x][y]=='.')
                                            ghost.ifcookie=1;
                                        else
                                            ghost.ifcookie=0;
                                        if(map.map[x][y]=='e')
                                            ghost.if_boost=1;
                                        else
                                            ghost.if_boost=0;
                                    }
                    }
    }
        if(possible>2)
        {
            srand(time(0));
            int los=1+rand()%4;

            if(los==1)
            {
                if(up)
                {
                    if(ghost.ifcookie!=0)
                    {
                        map.map[x][y]='.';
                        ghost.last_move='U';
                    }
                    if(ghost.if_boost!=0)
                    {
                        map.map[x][y]='e';
                        ghost.last_move='U';
                    }
                    if(ghost.ifcookie==0&&ghost.if_boost==0)
                    {
                        map.map[x][y]=' ';
                        ghost.last_move='U';
                    }
                    if(map.map[x-1][y]=='.')
                        ghost.ifcookie=1;
                    else
                        ghost.ifcookie=0;
                    if(map.map[x-1][y]=='e')
                        ghost.if_boost=1;
                    else
                        ghost.if_boost=0;
                    x--;
                }
                else
                    if(down)
                    {
                        if(ghost.ifcookie!=0)
                        {
                            map.map[x][y]='.';
                            ghost.last_move='D';
                        }
                        if(ghost.if_boost!=0)
                        {
                            map.map[x][y]='e';

                            ghost.last_move='D';
                        }
                        if(ghost.ifcookie==0&&ghost.if_boost==0)
                        {
                            map.map[x][y]=' ';
                            ghost.last_move='D';
                        }
                        if(map.map[x+1][y]=='.')
                            ghost.ifcookie=1;
                        else
                            ghost.ifcookie=0;
                        if(map.map[x+1][y]=='e')
                            ghost.if_boost=1;
                        else
                            ghost.if_boost=0;
                    }
                else
                        if(left)
                        {
                            if(ghost.ifcookie!=0)
                            {
                                map.map[x][y]='.';
                                y--;
                                ghost.last_move='L';
                            }
                            if(ghost.if_boost!=0)
                            {
                                map.map[x][y]='e';
                                y--;
                                ghost.last_move='L';
                            }
                            if(ghost.ifcookie==0&&ghost.if_boost==0)
                            {
                                map.map[x][y]=' ';
                                y--;
                                ghost.last_move='L';
                            }
                            if(map.map[x][y]=='.')
                                ghost.ifcookie=1;
                            else
                                ghost.ifcookie=0;
                            if(map.map[x][y]=='e')
                                ghost.if_boost=1;
                            else
                                ghost.if_boost=0;
                        }
                else
                            if(right)
                            {
                                if(ghost.ifcookie!=0)
                                {
                                    map.map[x][y]='.';
                                    y++;
                                    ghost.last_move='R';
                                }
                                if(ghost.if_boost!=0)
                                {
                                    map.map[x][y]='e';
                                    y++;
                                    ghost.last_move='R';
                                }
                                if(ghost.ifcookie==0&&ghost.if_boost==0)
                                {
                                    map.map[x][y]=' ';
                                    y++;
                                    ghost.last_move='R';
                                }
                                if(map.map[x][y]=='.')
                                    ghost.ifcookie=1;
                                else
                                    ghost.ifcookie=0;
                                if(map.map[x][y]=='e')
                                    ghost.if_boost=1;
                                else
                                    ghost.if_boost=0;
                            }

            }
            if(los==2)
            {
                if(down)
                {
                    if(ghost.ifcookie!=0)
                    {
                        map.map[x][y]='.';
                        x++;
                        ghost.last_move='D';
                    }
                    if(ghost.if_boost!=0)
                    {
                        map.map[x][y]='e';
                        x++;
                        ghost.last_move='D';
                    }
                    if(ghost.ifcookie==0&&ghost.if_boost==0)
                    {
                        map.map[x][y]=' ';
                        x++;
                        ghost.last_move='D';
                    }
                    if(map.map[x][y]=='.')
                        ghost.ifcookie=1;
                    else
                        ghost.ifcookie=0;
                    if(map.map[x][y]=='e')
                        ghost.if_boost=1;
                    else
                        ghost.if_boost=0;
                }
                else
                    if(left)
                    {
                        if(ghost.ifcookie!=0)
                        {
                            map.map[x][y]='.';
                            y--;
                            ghost.last_move='L';
                        }
                        if(ghost.if_boost!=0)
                        {
                            map.map[x][y]='e';
                            y--;
                            ghost.last_move='L';
                        }
                        if(ghost.ifcookie==0&&ghost.if_boost==0)
                        {
                            map.map[x][y]=' ';
                            y--;
                            ghost.last_move='L';
                        }
                        if(map.map[x][y]=='.')
                            ghost.ifcookie=1;
                        else
                            ghost.ifcookie=0;
                        if(map.map[x][y]=='e')
                            ghost.if_boost=1;
                        else
                            ghost.if_boost=0;
                    }
                else
                        if(right)
                        {
                            if(ghost.ifcookie!=0)
                            {
                                map.map[x][y]='.';
                                y++;
                                ghost.last_move='R';
                            }
                            if(ghost.if_boost!=0)
                            {
                                map.map[x][y]='e';
                                y++;
                                ghost.last_move='R';
                            }
                            if(ghost.ifcookie==0&&ghost.if_boost==0)
                            {
                                map.map[x][y]=' ';
                                y++;
                                ghost.last_move='R';
                            }
                            if(map.map[x][y]=='.')
                                ghost.ifcookie=1;
                            else
                                ghost.ifcookie=0;
                            if(map.map[x][y]=='e')
                                ghost.if_boost=1;
                            else
                                ghost.if_boost=0;
                        }
                else
                            if(up)
                            {
                                if(ghost.ifcookie!=0)
                                {
                                    map.map[x][y]='.';
                                    x--;
                                    ghost.last_move='U';
                                }
                                if(ghost.if_boost!=0)
                                {
                                    map.map[x][y]='e';
                                    x--;
                                    ghost.last_move='U';
                                }
                                if(ghost.ifcookie==0&&ghost.if_boost==0)
                                {
                                    map.map[x][y]=' ';
                                    x--;
                                    ghost.last_move='U';
                                }
                                if(map.map[x][y]=='.')
                                    ghost.ifcookie=1;
                                else
                                    ghost.ifcookie=0;
                                if(map.map[x][y]=='e')
                                    ghost.if_boost=1;
                                else
                                    ghost.if_boost=0;
                            }

            }
            if(los==3)
            {
                if(left)
                {
                    if(ghost.ifcookie!=0)
                    {
                        map.map[x][y]='.';
                        y--;
                        ghost.last_move='L';
                    }
                    if(ghost.if_boost!=0)
                    {
                        map.map[x][y]='e';
                        y--;
                        ghost.last_move='L';
                    }
                    if(ghost.ifcookie==0&&ghost.if_boost==0)
                    {
                        map.map[x][y]=' ';
                        y--;
                        ghost.last_move='L';
                    }
                    if(map.map[x][y]=='.')
                        ghost.ifcookie=1;
                    else
                        ghost.ifcookie=0;
                    if(map.map[x][y]=='e')
                        ghost.if_boost=1;
                    else
                        ghost.if_boost=0;
                }
                else
                    if(right)
                    {
                        if(ghost.ifcookie!=0)
                        {
                            map.map[x][y]='.';
                            y++;
                            ghost.last_move='R';
                        }
                        if(ghost.if_boost!=0)
                        {
                            map.map[x][y]='e';
                            y++;
                            ghost.last_move='R';
                        }
                        if(ghost.ifcookie==0&&ghost.if_boost==0)
                        {
                            map.map[x][y]=' ';
                            y++;
                            ghost.last_move='R';
                        }
                        if(map.map[x][y]=='.')
                            ghost.ifcookie=1;
                        else
                            ghost.ifcookie=0;
                        if(map.map[x][y]=='e')
                            ghost.if_boost=1;
                        else
                            ghost.if_boost=0;
                    }
                else
                        if(up)
                        {
                            if(ghost.ifcookie!=0)
                            {
                                map.map[x][y]='.';
                                x--;
                                ghost.last_move='U';
                            }
                            if(ghost.if_boost!=0)
                            {
                                map.map[x][y]='e';
                                x--;
                                ghost.last_move='U';
                            }
                            if(ghost.ifcookie==0&&ghost.if_boost==0)
                            {
                                map.map[x][y]=' ';
                                x--;
                                ghost.last_move='U';
                            }
                            if(map.map[x][y]=='.')
                                ghost.ifcookie=1;
                            else
                                ghost.ifcookie=0;
                            if(map.map[x][y]=='e')
                                ghost.if_boost=1;
                            else
                                ghost.if_boost=0;
                        }
                else
                            if(down)
                            {
                                if(ghost.ifcookie!=0)
                                {
                                    map.map[x][y]='.';
                                    x++;
                                    ghost.last_move='D';
                                }
                                if(ghost.if_boost!=0)
                                {
                                    map.map[x][y]='e';
                                    x++;
                                    ghost.last_move='D';
                                }
                                if(ghost.ifcookie==0&&ghost.if_boost==0)
                                {
                                    map.map[x][y]=' ';
                                    x++;
                                    ghost.last_move='D';
                                }
                                if(map.map[x][y]=='.')
                                    ghost.ifcookie=1;
                                else
                                    ghost.ifcookie=0;
                                if(map.map[x][y]=='e')
                                    ghost.if_boost=1;
                                else
                                    ghost.if_boost=0;
                            }
            }
            if(los==4)
            {
                if(right)
                {
                    if(ghost.ifcookie!=0)
                    {
                        map.map[x][y]='.';
                        y++;
                        ghost.last_move='R';
                    }
                    if(ghost.if_boost!=0)
                    {
                        map.map[x][y]='e';
                        y++;
                        ghost.last_move='R';
                    }
                    if(ghost.ifcookie==0&&ghost.if_boost==0)
                    {
                        map.map[x][y]=' ';
                        y++;
                        ghost.last_move='R';
                    }
                    if(map.map[x][y]=='.')
                        ghost.ifcookie=1;
                    else
                        ghost.ifcookie=0;
                    if(map.map[x][y]=='e')
                        ghost.if_boost=1;
                    else
                        ghost.if_boost=0;
                }
                else
                    if(up)
                    {
                        if(ghost.ifcookie!=0)
                        {
                            map.map[x][y]='.';
                            x--;
                            ghost.last_move='U';
                        }
                        if(ghost.if_boost!=0)
                        {
                            map.map[x][y]='e';
                            x--;
                            ghost.last_move='U';
                        }
                        if(ghost.ifcookie==0&&ghost.if_boost==0)
                        {
                            map.map[x][y]=' ';
                            x--;
                            ghost.last_move='U';
                        }
                        if(map.map[x][y]=='.')
                            ghost.ifcookie=1;
                        else
                            ghost.ifcookie=0;
                        if(map.map[x][y]=='e')
                            ghost.if_boost=1;
                        else
                            ghost.if_boost=0;
                    }
                else
                        if(down)
                        {
                            if(ghost.ifcookie!=0)
                            {
                                map.map[x][y]='.';
                                x++;
                                ghost.last_move='D';
                            }
                            if(ghost.if_boost!=0)
                            {
                                map.map[x][y]='e';
                                x++;
                                ghost.last_move='D';
                            }
                            if(ghost.ifcookie==0&&ghost.if_boost==0)
                            {
                                map.map[x][y]=' ';
                                x++;
                                ghost.last_move='D';
                            }
                            if(map.map[x][y]=='.')
                                ghost.ifcookie=1;
                            else
                                ghost.ifcookie=0;
                            if(map.map[x][y]=='e')
                                ghost.if_boost=1;
                            else
                                ghost.if_boost=0;
                        }
                else
                            if(left)
                            {
                                if(ghost.ifcookie!=0)
                                {
                                    map.map[x][y]='.';
                                    y--;
                                    ghost.last_move='L';
                                }
                                if(ghost.if_boost!=0)
                                {
                                    map.map[x][y]='e';
                                    y--;
                                    ghost.last_move='L';
                                }
                                if(ghost.ifcookie==0&&ghost.if_boost==0)
                                {
                                    map.map[x][y]=' ';
                                    y--;
                                    ghost.last_move='L';
                                }
                                if(map.map[x][y]=='.')
                                    ghost.ifcookie=1;
                                else
                                    ghost.ifcookie=0;
                                if(map.map[x][y]=='e')
                                    ghost.if_boost=1;
                                else
                                    ghost.if_boost=0;
                            }
        }
    }

    ghost.xg=x;
    ghost.yg=y;

    map.map[ghost.xg][ghost.yg]='A';

    if(1)
    {
    if(ghost.lp%2!=0)
    {
        map.xg1=ghost.xg;
        map.yg1=ghost.yg;
    }
    if(ghost.lp%2==0)
    {
        map.xg2=ghost.xg;
        map.yg2=ghost.yg;
    }
    ghost.lp++;
    }

}

void ghost_boost(){

    //tutaj tworze ruchy ducha po zjedzeniu przez pacmana wzmacniacza

}
